/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EntryRouteImport } from './routes/entry'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AgentProjectsRouteImport } from './routes/agent-projects'
import { Route as AgentBillableReportRouteImport } from './routes/agent-billable-report'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/reset-password.lazy').then((d) => d.Route),
)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))
const EntryRoute = EntryRouteImport.update({
  id: '/entry',
  path: '/entry',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/entry.lazy').then((d) => d.Route))
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/dashboard.lazy').then((d) => d.Route))
const AgentProjectsRoute = AgentProjectsRouteImport.update({
  id: '/agent-projects',
  path: '/agent-projects',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/agent-projects.lazy').then((d) => d.Route),
)
const AgentBillableReportRoute = AgentBillableReportRouteImport.update({
  id: '/agent-billable-report',
  path: '/agent-billable-report',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/agent-billable-report.lazy').then((d) => d.Route),
)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/agent.lazy').then((d) => d.Route))
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/admin.lazy').then((d) => d.Route))
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/agent': typeof AgentRoute
  '/agent-billable-report': typeof AgentBillableReportRoute
  '/agent-projects': typeof AgentProjectsRoute
  '/dashboard': typeof DashboardRoute
  '/entry': typeof EntryRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/agent': typeof AgentRoute
  '/agent-billable-report': typeof AgentBillableReportRoute
  '/agent-projects': typeof AgentProjectsRoute
  '/dashboard': typeof DashboardRoute
  '/entry': typeof EntryRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/agent': typeof AgentRoute
  '/agent-billable-report': typeof AgentBillableReportRoute
  '/agent-projects': typeof AgentProjectsRoute
  '/dashboard': typeof DashboardRoute
  '/entry': typeof EntryRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/agent'
    | '/agent-billable-report'
    | '/agent-projects'
    | '/dashboard'
    | '/entry'
    | '/login'
    | '/reset-password'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/agent'
    | '/agent-billable-report'
    | '/agent-projects'
    | '/dashboard'
    | '/entry'
    | '/login'
    | '/reset-password'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/agent'
    | '/agent-billable-report'
    | '/agent-projects'
    | '/dashboard'
    | '/entry'
    | '/login'
    | '/reset-password'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AgentRoute: typeof AgentRoute
  AgentBillableReportRoute: typeof AgentBillableReportRoute
  AgentProjectsRoute: typeof AgentProjectsRoute
  DashboardRoute: typeof DashboardRoute
  EntryRoute: typeof EntryRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entry': {
      id: '/entry'
      path: '/entry'
      fullPath: '/entry'
      preLoaderRoute: typeof EntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-projects': {
      id: '/agent-projects'
      path: '/agent-projects'
      fullPath: '/agent-projects'
      preLoaderRoute: typeof AgentProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-billable-report': {
      id: '/agent-billable-report'
      path: '/agent-billable-report'
      fullPath: '/agent-billable-report'
      preLoaderRoute: typeof AgentBillableReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AgentRoute: AgentRoute,
  AgentBillableReportRoute: AgentBillableReportRoute,
  AgentProjectsRoute: AgentProjectsRoute,
  DashboardRoute: DashboardRoute,
  EntryRoute: EntryRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
